export const frontRoutes = {
    home: '/dashboard',
    dashboard: '/dashboard',
    desempenho: '/desempenho',
    equipe: '/equipe',
    projetos: '/projetos',
    usuariosAdmin: '/usuarios',
    gestao: '/gestao',
    login: '/login',
    settings: '/settings',
} as const;

export const apiRoutes = {
    cargos: '/api/cargos',
    equipes: '/api/equipes',
    equipesTotalSubequipes: '/api/equipes/subequipes/total',
    historicoProgresso: '/api/historico-progresso',
    historicoProgressoUltimo: (id: number | string) => `/api/historico-progresso/tarefa/${id}/ultimo`,
    logProjeto: '/api/log-projeto',
    logSistema: '/api/log-sistema',
    metas: '/api/metas',
    projetos: '/api/projetos',
    projetosExcluidosHistorico: '/api/projetos/excluidos/historico',
    projetosExcluidosRestaurar: (id: number | string) => `/api/projetos/excluidos/${id}/restaurar`,
    authVerificar: '/api/auth/verificar',
    senhas: '/api/senhas',
    tarefas: '/api/tarefas',
    sprints: '/api/sprints',
    sprintsEncerrar: (id: number | string) => `/api/sprints/${id}/encerrar`,
    usuarios: '/api/usuarios',
    usuariosExcluidosHistorico: '/api/usuarios/excluidos/historico',
    usuariosExcluidosRestaurar: (id: number | string) => `/api/usuarios/excluidos/${id}/restaurar`,
    databaseBackup: '/api/database/backup',
    buscaGlobal: '/api/busca/global',
    notificacoes: '/api/notificacoes',
} as const;
